
services:
  mysql-container:
    image: mysql:8.0.33
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: obs_user
      MYSQL_USER: my_user
      MYSQL_PASSWORD: user_password
    volumes:
      - mysql_data:/var/lib/mysql

  obs_web:
    image: obs_web:0.0.1
    container_name: obs_web
    depends_on:
      - mysql-container
    ports:
      - "8080:8080"

volumes:
  mysql_data:
